# Generated by Django 5.0.2 on 2024-02-18 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project_manager",
            "0002_company_rename_usuario_userprofile_user_card_company_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="project_manager.company",
            ),
        ),
    ]
