# Generated by Django 5.0.2 on 2024-02-19 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_manager", "0003_alter_userprofile_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="company",
        ),
        migrations.AddField(
            model_name="board",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="project_manager.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="address",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="mail",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="nif",
            field=models.CharField(default="", max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="postalCode",
            field=models.CharField(default="", max_length=6),
            preserve_default=False,
        ),
    ]
