# Generated by Django 5.0.2 on 2024-02-25 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "project_manager",
            "0004_remove_card_company_board_company_company_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="board",
            unique_together={("name", "company")},
        ),
    ]
