# Generated by Django 5.0.2 on 2024-02-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_manager", "0005_alter_board_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="rol",
            field=models.CharField(
                choices=[
                    ("USER", "Usuario"),
                    ("ADMIN_COMPANY", "Administrador Compañia"),
                ],
                default="USER",
                max_length=20,
            ),
        ),
    ]
