# Generated by Django 5.0.2 on 2024-02-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_manager", "0006_userprofile_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="deletion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="board",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
