# Generated by Django 5.0.2 on 2024-02-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_manager", "0009_list_creat_by_alter_list_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
