# Generated by Django 5.0.2 on 2024-03-04 18:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_manager", "0011_list_deleted_by_list_deletion_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="assigned_users",
            field=models.ManyToManyField(blank=True, to="project_manager.userprofile"),
        ),
        migrations.AddField(
            model_name="card",
            name="creation_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="deletion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="card",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
