# Generated by Django 5.0.2 on 2024-03-12 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project_manager", "0012_card_assigned_users_card_creation_date_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="card",
            unique_together={("name", "lista")},
        ),
    ]
